apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  storageClassName: mylocalstorage
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteOnce
--- 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-storage
spec:
  storageClassName: mylocalstorage
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
      path: /mnt/yeahyeah
      type: DirectoryOrCreate

